# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'PromiseKitDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for PromiseKitDemo
#  pod 'PromiseKit','~> 4.5.1'
    pod 'PromiseKit'


end
