
platform :ios, '9.0'

use_frameworks!

	def net_pod
		pod    'QIYU_iOS_SDK'
    end



target 'QIYUDemo' do 

	net_pod

end 

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'HandyJSON'
            target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
    end
end