# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!


    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    
    
    def ui_pods

        pod 'PullToRefreshKit' #Swift版下拉刷新，支持横向侧拉
        pod 'SnapKit'
        pod 'ESTabBarController-swift', '2.4'
        # pod 'BetterSegmentedControl', '~> 0.8' #https://github.com/gmarm/BetterSegmentedControl
        pod 'HMSegmentedControl', '1.5.3', :inhibit_warnings => true
        pod 'IQKeyboardManagerSwift'
        pod 'InputKitSwift', '~> 1.1.16'
        pod 'Kingfisher'
        pod 'CoreAnimator', '~> 2.1.3'
        
    end

    def net_pod
        pod 'Format' # Simple formatting syntax for decimal numbers, currency, mass, addresses, ordinal numbers and hexadecimal colors.
        pod 'Moya'
        pod 'Moya/RxSwift'
        pod 'RxSwift' 
        pod 'PromiseKit','~> 4.5.1'
        pod 'PromiseKit/Alamofire'
        pod 'HandyJSON' #A Json Serialization & Deserialization Library for Swift
    end

    def common_pod
        pod 'SwifterSwift'
        pod 'MagicalRecord', '2.3.2' #Super Awesome Easy Fetching for Core Data 1!!!11!!!!1!.
        pod 'R.swift'

    end

    def sdk_pods
        pod 'WebViewJavascriptBridge', :git => 'https://github.com/AwesomeDennis/WebViewJavascriptBridge', :tag => 'v6.0.6'
#        pod 'FCScanLibrary', :git => 'http://gitlab.fclassroom.cn/TeachingServiceOutputTeam/app/Fclassroom-iOS-Scan.git', :tag => '0.0.4'
        pod 'Fabric'
        pod 'Crashlytics'
    end
    
    
    def custom_pods
        pod 'RxCocoa'
    	pod 'RxSwift'
        pod 'RxDataSources'
    end
    
     #A lightweight, pure-Swift library for downloading and caching images from the web.
    target 'TableView_RxSwift' do  
        # ui_pods
        # common_pod
        # net_pod
        # sdk_pods
        custom_pods
    end

    post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'HandyJSON' || target.name == 'Format' || target.name == 'ESTabBarController-swift'
            target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
    end
end
